# Generated by Django 3.1.14 on 2022-12-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0002_auto_20221221_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='about_profile',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='alternate_contact',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='primary_contact',
            field=models.IntegerField(),
        ),
    ]
