# Generated by Django 3.1.14 on 2022-12-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0003_auto_20221221_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='alternate_contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='primary_contact',
            field=models.CharField(max_length=10),
        ),
    ]
