# Generated by Django 3.1.14 on 2022-11-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
